### ISSUE TITLE
Unable to to enable video camera on Mac desktop when Jitsi is embedded

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-jitsi#120]
When using Jitsi with `Embed Jitsi video inside Mattermost` I'm not able to turn on my camera when using Mattermost Mac OS desktop client v4.5.0 Running build https://github.com/mattermost/mattermost-plugin-jitsi/commit/013533b3f7a835e4cb279a8b3c6cf119b6625038

I see the follow error message
![Screen Shot 2020-06-24 at 2 32 13 PM](https://user-images.githubusercontent.com/35588783/85617851-ea5d7b80-b62d-11ea-9d08-149f973282be.png)
<img>

- This does not occur in Chrome or when `Embed Jitsi video inside Mattermost` is disabled
- Occurs for me on both hosted and cloud version of Jitsi
- On a diffrent Windows machine I don't see the issue

Seems possible I have some OS level issue causing this. Please see if you can reproduce. 
Steps:
- Setup Jisti 
- Enable `Embed Jitsi video inside Mattermost` 
- Connect to server from desktop
- Join a meeting
**Observed**
- Camera remains disabled (normally turns on after a couple seconds)
- Attempting to enable it shows a error in the Jisti UI

**Comment by jespino** [comment]
@DHaussermann yes, looks like permissions related like the share screen problem seen before.

**Comment by jespino** [comment]
I can explicitly try to request permissions using `https://www.electronjs.org/docs/api/system-preferences#systempreferencesaskformediaaccessmediatype-macos`

**Comment by jespino** [comment]
Camera is working for me in desktop app 4.4.0 in Arch Linux, maybe is mac thing

**Comment by amyblais** [comment]
Please see some additional details here https://github.com/mattermost/desktop/issues/1330#issuecomment-649377999.

**Comment by dpanic** [comment]
> Camera is working for me in desktop app 4.4.0 in Arch Linux, maybe is mac thing

Yes it is MacOS thing...App needs to be signed with entitlements 

https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_device_camera
https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_device_microphone

**Comment by alefattorini** [comment]
Any news on this? It's a bit confusing switching to the web version in order to use the jitsi plugin

**Comment by amyblais** [comment]
Unsure if it helps, but in desktop app v4.6.2 we fixed an issue where macOS entitlements had not been enabled for using camera and microphone on the Desktop App for third-party plugins such as Jitsi -- https://docs.mattermost.com/help/apps/desktop-changelog.html#release-v4-6

**Comment by dpanic** [comment]
QA in my company tested, and it still doesn't work unfortunately

**Comment by estebanz01** [comment]
I confirm that updating to version 4.6.2 works. I needed to reinstall the app (delete it and add new version) so the permissions can work.

**Comment by hanzei** [comment]
@dpanic Did you test after reinstalling the app?

**Comment by dpanic** [comment]
Will retest. It didn't worked than (around March this year)

![Screenshot from 2021-05-28 09-39-59](https://user-images.githubusercontent.com/346557/119948272-f453d100-bf98-11eb-8f2a-26177e17cfc9.png)

**Comment by larkox** [comment]
@Willyfrog Any thoughts on this?

**Comment by Willyfrog** [comment]
if you never got any permission request might be because you already especified those permissions in the OS settings? that happened to me on big sur, if I chose not to permit access, I'd have to go to system preferences -> security & privacy -> camera and allow mattermost to use it. On catalina the path might be different.
